defaults: &defaults-node
  working_directory: ~/demo-ci-cd
  docker:
    - image: circleci/python:2.7-node

version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  build:
    <<: *defaults-node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ./dist
          paths:
            - ./*
  #test:
  #  <<: *defaults-node
  #  steps:
  #    - checkout
  #    - run: npm install
  #    - run: npm run test
  deploy:
    docker:
      - image: circleci/python:2.7-node
    environment:
      AWS_REGION: us-east-1
    working_directory: ~/demo-ci-cd
    steps:
      - attach_workspace : 
          at: ~/demo-ci-cd
      - checkout
      - run: npm install
      - run: npm run build
      - aws-s3/sync:
        from: dist
        to: 's3://dima-f1-ci-cd-test/'
        arguments: |
          --acl public-read \
          --cache-control "max-age=86400" \
        overwrite: true
workflows:
  version: 2.1
  build:
    jobs:
      - build:
        filters:
          branches:
            only: master
      #- test:
      #  filters:
      #    branches:
      #      only: master
      #    requires: # We only run the "hold" job when test2 has succeeded
      #      - build
      - hold: # <<< A job that will require manual approval in the CircleCI web application.
        type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
        requires: # We only run the "hold" job when test2 has succeeded
          - build
      #On approval of the `hold` job, any successive job that requires the `hold` job will run. 
      #In this case, a user is manually triggering the deploy job.
      - deploy:
        requires:
          - hold